# Generated by Django 2.0.5 on 2018-09-12 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('name', models.CharField(max_length=256)),
                ('container', models.CharField(max_length=100)),
                ('recipe_steps', models.TextField()),
                ('recipe_id', models.CharField(max_length=4)),
                ('comments', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('number_requested', models.IntegerField()),
                ('date_requested', models.DateTimeField()),
                ('date_needed', models.DateField()),
                ('initial_comments', models.TextField(max_length=180)),
                ('completed', models.BooleanField(default=False)),
                ('date_cancelled', models.DateTimeField(blank=True, null=True)),
                ('batchid', models.CharField(max_length=150)),
                ('container', models.CharField(max_length=150)),
                ('volume_made', models.IntegerField()),
                ('number_made', models.IntegerField()),
                ('total_volume_made', models.IntegerField()),
                ('date_made', models.DateTimeField(blank=True, null=True)),
                ('final_recipe', models.TextField(max_length=180)),
                ('final_comments', models.TextField(max_length=180)),
                ('number_contaminated', models.IntegerField()),
                ('date_contamination_found', models.DateField(blank=True, null=True)),
                ('number_wasted', models.IntegerField()),
                ('date_wasted', models.DateField(blank=True, null=True)),
                ('waste_comments', models.TextField(max_length=180)),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by_user', to=settings.AUTH_USER_MODEL)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_by_user', to=settings.AUTH_USER_MODEL)),
                ('media_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediarecipes.Recipe')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('id', 'recipe_steps')},
        ),
    ]
