# Generated by Django 2.0.5 on 2018-11-15 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('name', models.CharField(max_length=256)),
                ('container', models.CharField(choices=[('a', 'Split Plate'), ('b', 'Thin Plate'), ('c', 'Thick Plate'), ('d', 'Plant Con'), ('e', 'Sundae Cup'), ('f', 'other')], max_length=100)),
                ('recipe_id', models.CharField(max_length=4, unique=True)),
                ('comments', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recipe_id'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('number_requested', models.IntegerField()),
                ('date_requested', models.DateTimeField()),
                ('date_needed', models.DateField()),
                ('initial_comments', models.TextField(max_length=180)),
                ('completed', models.BooleanField(default=False)),
                ('date_cancelled', models.DateTimeField(blank=True, null=True)),
                ('batchid', models.CharField(blank=True, max_length=150)),
                ('container', models.CharField(blank=True, max_length=150)),
                ('volume_made', models.IntegerField(blank=True, null=True)),
                ('number_made', models.IntegerField(blank=True, null=True)),
                ('total_volume_made', models.IntegerField(blank=True, null=True)),
                ('date_made', models.DateTimeField(blank=True, null=True)),
                ('final_recipe', models.TextField(blank=True, max_length=180)),
                ('final_comments', models.TextField(blank=True, max_length=180)),
                ('number_contaminated', models.IntegerField(blank=True, null=True)),
                ('date_contamination_found', models.DateField(blank=True, null=True)),
                ('number_wasted', models.IntegerField(blank=True, null=True)),
                ('date_wasted', models.DateField(blank=True, null=True)),
                ('waste_comments', models.TextField(blank=True, max_length=180)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by_user', to=settings.AUTH_USER_MODEL)),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_by_user', to=settings.AUTH_USER_MODEL)),
                ('media_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediarecipes.Recipe')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pHStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediarecipes.Step')),
                ('ingredient', models.TextField(choices=[('1', 'KOH'), ('2', 'NaOH'), ('3', 'HCl')])),
                ('ph_to', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            bases=('mediarecipes.step',),
        ),
        migrations.CreateModel(
            name='ReagentStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediarecipes.Step')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.TextField(choices=[('1', 'g'), ('2', 'mg'), ('3', 'ug'), ('4', 'M'), ('5', 'mM'), ('6', 'uM')])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Chemical')),
            ],
            bases=('mediarecipes.step',),
        ),
        migrations.CreateModel(
            name='SterilizeStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediarecipes.Step')),
                ('sterilize', models.TextField(choices=[('1', 'Autoclave for 25 minutes'), ('2', 'Filter Sterilize')])),
            ],
            bases=('mediarecipes.step',),
        ),
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediarecipes.Recipe'),
        ),
    ]
