# Generated by Django 2.0.5 on 2019-01-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediarecipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('1', 'Queued'), ('2', 'Started'), ('3', 'Complete'), ('4', 'Canceled')], default='1', max_length=100),
            preserve_default=False,
        ),
    ]
