# Generated by Django 2.0.5 on 2018-09-12 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediarecipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['recipe_id']},
        ),
        migrations.AlterField(
            model_name='request',
            name='batchid',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='request',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='container',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='request',
            name='final_comments',
            field=models.TextField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='request',
            name='final_recipe',
            field=models.TextField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='request',
            name='made_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_contaminated',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_made',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_wasted',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='total_volume_made',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='volume_made',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='waste_comments',
            field=models.TextField(blank=True, max_length=180),
        ),
    ]
