# Generated by Django 2.0.5 on 2018-09-12 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediarecipes', '0003_auto_20180912_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
