# Generated by Django 2.0.5 on 2018-09-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediarecipes', '0004_auto_20180912_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='container',
            field=models.CharField(choices=[('a', 'Split Plate'), ('b', 'Thin Plate'), ('c', 'Thick Plate'), ('d', 'Plant Con'), ('e', 'Sundae Cup'), ('f', 'other')], max_length=100),
        ),
    ]
