# Generated by Django 2.0.5 on 2018-09-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180913_1544'),
        ('mediarecipes', '0005_auto_20180918_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.TextField(choices=[('1', 'g'), ('2', 'mg'), ('3', 'ug'), ('4', 'M'), ('5', 'mM'), ('6', 'uM')])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Chemical')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediarecipes.Recipe'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_steps',
        ),
    ]
