# Generated by Django 2.0.5 on 2018-11-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediarecipes', '0006_auto_20180926_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='pHStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('ingredient', models.TextField(choices=[('1', 'KOH'), ('2', 'NaOH'), ('3', 'HCl')])),
                ('ph_to', models.DecimalField(decimal_places=2, max_digits=4)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediarecipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='SterilizeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('sterilize', models.TextField(choices=[('1', 'Autoclave for 25 minutes'), ('2', 'Filter Sterilize')])),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediarecipes.Recipe')),
            ],
        ),
    ]
