# Generated by Django 2.0.5 on 2018-11-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediarecipes', '0007_phstep_sterilizestep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_id',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
