# Generated by Django 2.0.5 on 2018-11-15 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_made', models.DateTimeField()),
                ('batchid', models.CharField(max_length=256)),
                ('filtered', models.BooleanField()),
                ('volume', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['bottle', 'concentration'],
            },
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256)),
                ('catalog_number', models.CharField(max_length=256)),
                ('base_volume', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('lot_number', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_volume', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('recieved', models.DateField()),
                ('date_opened', models.DateTimeField(blank=True, null=True)),
                ('date_discarded', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['chemical'],
            },
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('atomic_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cas_number', models.CharField(max_length=25, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chemical',
            unique_together={('name', 'atomic_weight')},
        ),
        migrations.AddField(
            model_name='bottle',
            name='chemical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Chemical'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='discarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discarded_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bottle',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opened_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bottle',
            name='recieved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additive',
            name='bottle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Bottle'),
        ),
        migrations.AddField(
            model_name='additive',
            name='made_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
