# Generated by Django 2.0.5 on 2018-09-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180912_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='cas_number',
            field=models.CharField(default='4697-36-3', max_length=25),
            preserve_default=False,
        ),
    ]
