# Generated by Django 2.0.5 on 2018-09-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_chemical_cas_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='cas_number',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
